### ISSUE TITLE
Provide additional restriction via Namespace and and local name Regex

### ISSUE THREAD

**Issue by nichtich** [programmfabrik/easydb-custom-data-type-link#1]
- namespace: fixed prefix, e.g. `http://glottolog.org/resource/languoid/id/`
- reexp: to match the local name part after the prefix, e.g. `^[a-z]{4}[0-9]{4}$`

**Comment by nichtich** [comment]
corresponding internal ticket: https://tickets.programmfabrik.de/ticket/38817

**Comment by KlausThornProgrammfabrik** [comment]
Thanks you for your input and to also use our company's ticket system!

We will disable github issues and concentrate on our internal ticket system. you can use it by just writing to support@programmfabrik.de
