### ISSUE TITLE
remove "_fulltext.text" from "buildData"-function

### ISSUE THREAD

**Issue by StiftungAusNachlass** [programmfabrik/easydb-custom-data-type-link#4]
Due to https://docs.easydb.de/en/technical/plugins/customdatatype/#general-keys filling "_fulltext.text" with a string is needless and / or deprecated. I suggest to remove this line:

https://github.com/programmfabrik/easydb-custom-data-type-link/blob/e10b1478fea0fc9b56c0f041ba4ead1201606afd/src/webfrontend/CustomDataTypeLink.coffee#L668

**Comment by KlausThornProgrammfabrik** [comment]
Thank you for your input. And sorry to let it hanging here.

We will disable github issues to prevent this in the future.

You can write to support@programmfabrik.de
